# Site settings
title: High Fidelity Docs
email: contact@highfidelity.io
description: "Developer documentation for High Fidelity"
baseurl: ""
url: "http://docs.highfidelity.io"
twitter_username: highfidelityinc
github_username:  highfidelity

# Build settings
markdown: kramdown
permalink: pretty

# Content settings
category-list: [api, c++, javascript]