# Site settings
title: High Fidelity Docs
email: contact@highfidelity.io
description: "Developer documentation for High Fidelity"
baseurl: ""
url: "http://docs.highfidelity.io"
twitter_username: highfidelityinc
github_username:  highfidelity
sub_base_path: ""
base_github_url: "https://github.com/highfidelity/hifi-docs"

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
permalink: pretty
highlighter: pygments

collections:
  api:
    output: true
  articles:
    output: true
  managing:
    output: ture
  build-from-source:
    output: ture
  diagrams:
    output: ture
  
article-categories: [getting-started, scripts, settings, avatars, devices, "voxels-meshes & particles", audio]
managing-categories: [assignment-clients, domains]
api-categories: [avatar, particles, voxels, audio]


# API content settings
#api-section-list: [avatars, particles, voxels, audio]
#api-category-list: [properties, functions, attachments, animations]

# Article content settings
#article-section-list: [getting-started, scripts, settings, avatars, voxels, audio]
